/*
SQLyog Ultimate v8.32 
MySQL - 5.7.20-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `representive` (
	`sName` varchar (33),
	`cdistricId` double ,
	`name` varchar (150),
	`year` double ,
	`party` varchar (150),
	`rid` double ,
	`photoUrl` varchar (150)
); 
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Mark Sanford','1997','R','72',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Floyd Davidson Spence','1997','R','73',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','Lindsey Olin Graham ','1997','R','74',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','Bob Inglis','1997','R','75',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','ohn McKee Spratt','1997','D','76',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','1997','D','77',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Mark Sanford','1999','R','78',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Floyd Davidson Spence','1999','R','79',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','Lindsey Olin Graham ','1999','R','80',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','James Warren DeMint','1999','R','81',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','ohn McKee Spratt','1999','D','82',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','1999','D','83',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Henry Edward Brown Jr.','2001','R','84',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Joe Wilson','2001','R','85',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','Lindsey Olin Graham ','2001','R','86',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','James Warren DeMint','2001','R','87',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','ohn McKee Spratt','2001','D','88',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','2001','D','89',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Henry Edward Brown Jr.','2003','R','90',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Joe Wilson','2003','R','91',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','James Gresham Barrett ','2003','R','92',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','James Warren DeMint','2003','R','93',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','ohn McKee Spratt','2003','D','94',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','2003','D','95',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Henry Edward Brown Jr.','2005','R','96',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Joe Wilson','2005','R','97',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','James Gresham Barrett ','2005','R','98',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','Bob Inglis','2005','R','99',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','ohn McKee Spratt','2005','D','100',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','2005','D','101',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Henry Edward Brown Jr.','2007','R','102',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Joe Wilson','2007','R','103',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','James Gresham Barrett ','2007','R','104',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','Bob Inglis','2007','R','105',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','ohn McKee Spratt','2007','D','106',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','2007','D','107',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Henry Edward Brown Jr.','2009','R','108',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Joe Wilson','2009','R','109',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','James Gresham Barrett ','2009','R','110',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','Bob Inglis','2009','R','111',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','ohn McKee Spratt','2009','D','112',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','2009','D','113',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Timothy Eugene Scott','2011','R','114',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Joe Wilson','2011','R','115',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','Jeffrey Darren Duncan','2011','R','116',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','Trey Gowdy','2011','R','117',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','John Michael Mulvaney','2011','R','118',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','2011','D','119',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Mark Sanford','2013','R','120',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Joe Wilson','2013','R','121',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','Jeffrey Darren Duncan','2013','R','122',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','Trey Gowdy','2013','R','123',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','John Michael Mulvaney','2013','R','124',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','2013','D','125',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','7','Hugh Thompson Rice','2013','R','126',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Mark Sanford','2015','R','127',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Joe Wilson','2015','R','128',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','Jeffrey Darren Duncan','2015','R','129',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','Trey Gowdy','2015','R','130',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','John Michael Mulvaney','2015','R','131',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','2015','D','132',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','7','Hugh Thompson Rice','2015','R','133',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','1','Mark Sanford','2017','R','134',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','2','Joe Wilson','2017','R','135',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','3','Jeffrey Darren Duncan','2017','R','136',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','4','Trey Gowdy','2017','R','137',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','5','Ralph Warren Norman','2017','R','138',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','6','James Enos Clyburn','2017','D','139',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','John Edward Sununu','1997','R','140',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','1997','R','141',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','John Edward Sununu','1999','R','142',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','1999','R','143',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','John Edward Sununu','2001','R','144',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','2001','R','145',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Jeb Bradley','2003','R','146',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','2003','R','147',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Jeb Bradley','2005','R','148',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','2005','R','149',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Carol Shea-Porter','2007','D','150',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Paul William Hodes','2007','D','151',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Carol Shea-Porter','2009','D','152',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Paul William Hodes','2009','D','153',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Frank Christopher Guinta','2011','R','154',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','2011','R','155',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Carol Shea-Porter','2013','D','156',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Ann McLane Kuster','2013','D','157',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Frank Christopher Guinta','2015','R','158',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Ann McLane Kuster','2015','D','159',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Carol Shea-Porter','2017','D','160',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','John Edward Sununu','1997','R','161',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','1997','R','162',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','John Edward Sununu','1999','R','163',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','1999','R','164',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','John Edward Sununu','2001','R','165',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','2001','R','166',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Jeb Bradley','2003','R','167',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','2003','R','168',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Jeb Bradley','2005','R','169',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','2005','R','170',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Carol Shea-Porter','2007','D','171',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Paul William Hodes','2007','D','172',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Carol Shea-Porter','2009','D','173',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Paul William Hodes','2009','D','174',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Frank Christopher Guinta','2011','R','175',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Charlie Bass ','2011','R','176',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Carol Shea-Porter','2013','D','177',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Ann McLane Kuster','2013','D','178',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','1','Frank Christopher Guinta','2015','R','179',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Ann McLane Kuster','2015','D','180',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('NH','2','Ann McLane Kuster','2017','D','181',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','1997','D','182',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','David Evans Skaggs ','1997','D','183',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','Stephen Scott Emory McInnis','1997','R','184',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Robert Warren Schaffer','1997','R','185',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Joel Maurice Hefley','1997','R','186',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Dan Schaefer','1997','R','187',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','1999','D','188',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Mark Emery Udall','1999','D','189',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','Stephen Scott Emory McInnis','1999','R','190',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Robert Warren Schaffer','1999','R','191',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Robert Warren Schaffer','1999','R','192',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Thomas Gerard Tancredo','1999','R','193',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','2001','D','194',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Mark Emery Udall','2001','D','195',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','Stephen Scott Emory McInnis','2001','R','196',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Robert Warren Schaffer','2001','R','197',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Robert Warren Schaffer','2001','R','198',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Thomas Gerard Tancredo','2001','R','199',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','2003','D','200',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Mark Emery Udall','2003','D','201',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','Stephen Scott Emory McInnis','2003','R','202',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Marilyn Neoma Musgrave','2003','R','203',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Robert Warren Schaffer','2003','R','204',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Thomas Gerard Tancredo','2003','R','205',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','7','Robert Louis Beauprez','2003','R','206',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','2005','D','207',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Mark Emery Udall','2005','D','208',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','John Tony Salazar ','2005','D','209',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Marilyn Neoma Musgrave','2005','R','210',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Robert Warren Schaffer','2005','R','211',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Thomas Gerard Tancredo','2005','R','212',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','7','Thomas Gerard Tancredo','2005','R','213',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','2007','D','214',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Mark Emery Udall','2007','D','215',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','John Tony Salazar ','2007','D','216',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Marilyn Neoma Musgrave','2007','R','217',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Douglas L. Lamborn','2007','R','218',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Thomas Gerard Tancredo','2007','R','219',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','7','Edwin George Perlmutter','2007','D','220',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','2009','D','221',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Jared Schutz Polis','2009','D','222',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','John Tony Salazar ','2009','D','223',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Betsy Markey','2009','D','224',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Douglas L. Lamborn','2009','R','225',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Michael Howard Coffman','2009','R','226',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','7','Edwin George Perlmutter','2009','D','227',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','2011','D','228',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Jared Schutz Polis','2011','D','229',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','Scott R. Tipton','2011','R','230',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Cory Scott Gardner','2011','R','231',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Douglas L. Lamborn','2011','R','232',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Michael Howard Coffman','2011','R','233',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','7','Edwin George Perlmutter','2011','D','234',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','2013','D','235',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Jared Schutz Polis','2013','D','236',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','Scott R. Tipton','2013','R','237',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Cory Scott Gardner','2013','R','238',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Douglas L. Lamborn','2013','R','239',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Michael Howard Coffman','2013','R','240',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','7','Edwin George Perlmutter','2013','D','241',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','2015','D','242',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Jared Schutz Polis','2015','D','243',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','Scott R. Tipton','2015','R','244',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Kenneth Robert Buck ','2015','R','245',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Douglas L. Lamborn','2015','R','246',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Michael Howard Coffman','2015','R','247',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','7','Edwin George Perlmutter','2015','D','248',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','1','Diana Louise DeGette','2017','D','249',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','2','Jared Schutz Polis','2017','D','250',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','3','Scott R. Tipton','2017','R','251',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','4','Kenneth Robert Buck ','2017','R','252',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','5','Douglas L. Lamborn','2017','R','253',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','6','Michael Howard Coffman','2017','R','254',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('SC','7','Hugh Thompson Rice','2017','R','255',NULL);
insert into `representive` (`sName`, `cdistricId`, `name`, `year`, `party`, `rid`, `photoUrl`) values('CO','7','Edwin George Perlmutter','2017','D','256',NULL);
